In [1]:
import pandas as pd

In [11]:
bond=pd.read_csv("jamesbond.csv")

In [12]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

##  The .set_index() and .reset_index() Methods

In [13]:
bond.set_index("Film" , inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [14]:
bond.reset_index(inplace = True)
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

## Retrieve Rows by Index Label with .loc[]

In [19]:
bond.sort_index(inplace=True)

In [20]:
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [36]:
bond.reset_index(inplace = True)
bond.loc[6]

index                                              6
Film                 On Her Majesty's Secret Service
Year                                            1969
Actor                                 George Lazenby
Director                               Peter R. Hunt
Box Office                                     291.5
Budget                                          37.3
Bond Actor Salary                                0.6
Name: 6, dtype: object

In [52]:
# bond.loc["xyz"]

In [37]:
bond.set_index("Film" , inplace=True)
bond.loc["Casino Royale"]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
Casino Royale,4,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,22,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3

In [41]:
bond.loc["The Living Daylights":"Skyfall"]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
The Living Daylights,16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,17,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,18,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,20,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,21,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,22,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,23,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,24,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [42]:
bond.loc["Skyfall":]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
Skyfall,24,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,25,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [43]:
bond.loc[["Thunderball", "The Living Daylights"]]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
Thunderball,3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
The Living Daylights,16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [44]:
bond.loc[["Thunderball", "The Living Daylights", "Tomorrow Never Dies"]]

,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,,
Thunderball,3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
The Living Daylights,16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Tomorrow Never Dies,19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0

In [45]:
"xyz" in bond.index

False

In [50]:
bond.reset_index(inplace = True)
bond.loc[0:5]

,Film,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,0,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,2,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,4,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,5,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Retrieve Rows by Index Position with .iloc[]

In [51]:
bond.loc[15]
bond.iloc[14]

Film                   Octopussy
index                         14
Year                        1983
Actor                Roger Moore
Director               John Glen
Box Office                 373.8
Budget                      53.9
Bond Actor Salary            7.8
Name: 14, dtype: object

In [52]:
bond.iloc[15:20]

,Film,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
15,A View to a Kill,15,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,17,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,18,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0

In [53]:
bond.iloc[[15,20]]

,Film,index,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
15,A View to a Kill,15,1985,Roger Moore,John Glen,275.2,54.5,9.1
20,The World Is Not Enough,20,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

In [92]:
bond=pd.read_csv("jamesbond.csv")
bond.set_index("Film" , inplace=True)
bond.sort_index(inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [55]:
bond.iloc[10]

Year                           1989
Actor                Timothy Dalton
Director                  John Glen
Box Office                    250.9
Budget                         56.7
Bond Actor Salary               7.9
Name: Licence to Kill, dtype: object

In [56]:
bond.iloc[20:]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [57]:
bond.iloc[[10, 15]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

## The Catch-All .ix[] Method

In [91]:
# bond.ix["GoldenEye"]  not working

In [94]:
# bond.ix[20] .ix is deprecated

## Second Arguments to .loc[], .iloc[], and .ix[] Methods

In [58]:
bond.loc["Licence to Kill", "Actor": "Director"] #Sequently

Actor       Timothy Dalton
Director         John Glen
Name: Licence to Kill, dtype: object

In [59]:
bond.loc["Licence to Kill", ["Actor", "Budget", "Year"]] #Sequently

Actor     Timothy Dalton
Budget              56.7
Year                1989
Name: Licence to Kill, dtype: object

In [104]:
bond.iloc[14, 2]

'John Glen'

In [105]:
bond.iloc[14, 2:6]

Director             John Glen
Box Office               373.8
Budget                    53.9
Bond Actor Salary          7.8
Name: Octopussy, dtype: object

In [60]:
bond.iloc[14, [2,3,5,1]]

Director               John Glen
Box Office                 373.8
Bond Actor Salary            7.8
Actor                Roger Moore
Name: Octopussy, dtype: object

##  Set New Values for a Specific Cell or Row

In [61]:
 bond.loc["Dr. No", "Actor"] = "Bilal Hameed"

In [62]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal Hameed,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [65]:
bond.loc["From Russia with Love", ["Actor","Director","Box Office","Budget","Bond Actor Salary"]]=["Asfand","Zia","852","555","456"]

In [66]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal Hameed,Terence Young,448.8,7,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [67]:
bond.loc["Dr. No", ["Actor", "Box Office", "Bond Actor Salary"]]=["Bilal", "India", "8.2"]

In [68]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Set Multiple Values in DataFrame

In [69]:
mask=bond["Actor"] == "Sean Connery"
mask

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                             False
For Your Eyes Only                 False
From Russia with Love              False
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [70]:
bond[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [71]:
bond[mask]["Actor"] = "Sir Sean Connery"
bond

C:\Users\Bilal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [72]:
bond[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [73]:
df2=bond[mask]
df2["Actor"] = "Sir Sean Connery"
df2
# bond

C:\Users\Bilal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380,86,NaN
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [74]:
#here its go...

In [75]:
bond.loc[mask, "Actor"] = "Bilal Hameed"

In [76]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Bilal Hameed,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Bilal Hameed,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Bilal Hameed,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Bilal Hameed,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Bilal Hameed,Lewis Gilbert,514.2,59.9,4.4

In [213]:
# Back to orignal

In [77]:
mask1=bond["Actor"]=="Bilal Hameed"
mask1

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                             False
For Your Eyes Only                 False
From Russia with Love              False
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [78]:
bond.loc[mask, "Actor"] = "Sean Connery"

In [79]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Rename Index Labels or Columns in a DataFrame

In [80]:
bond.rename(columns={"Year":"Release Date"}, inplace=True)

In [81]:
bond

,Release Date,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [82]:
bond.rename(index={"Dr. No":"Doctor. No", "GoldenEye": "Golden Eye"}, inplace= True)

In [83]:
bond.columns

Index(['Release Date', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='object')

In [84]:
bond.columns=["A", "B", "C", "D", "E", "F"]

In [85]:
bond

,A,B,C,D,E,F
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Doctor. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Delete Rows or Columns from a DataFrame

In [86]:
bond.drop("Thunderball")

,A,B,C,D,E,F
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Doctor. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [87]:
bond.drop(["Skyfall", "Spectre", "The Spy Who Loved Me" ])

,A,B,C,D,E,F
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315,85,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Doctor. No,1962,Bilal,Terence Young,India,7,8.2
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Asfand,Zia,852,555,456
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380,86,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334,27.7,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [255]:
bond.drop("Box Office", axis=1)

,Year,Actor,Director,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,Roger Moore,John Glen,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,59.9,4.4

In [88]:
bond.drop(["Box Office", "Year"], axis=1)

KeyError: "['Box Office' 'Year'] not found in axis"

In [263]:
bond.drop(labels=["Box Office", "Year"], axis=1)

,Actor,Director,Budget,Bond Actor Salary
Film,,,,
A View to a Kill,Roger Moore,John Glen,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,145.3,3.3
Casino Royale,David Niven,Ken Hughes,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,154.2,17.9
Dr. No,Sean Connery,Terence Young,7.0,0.6
For Your Eyes Only,Roger Moore,John Glen,60.2,NaN
From Russia with Love,Sean Connery,Terence Young,12.6,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,76.9,5.1
Goldfinger,Sean Connery,Guy Hamilton,18.6,3.2
Licence to Kill,Timothy Dalton,John Glen,56.7,7.9
Live and Let Die,Roger Moore,Guy Hamilton,30.8,NaN
Moonraker,Roger Moore,Lewis Gilbert,91.5,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,86.0,NaN
Octopussy,Roger Moore,John Glen,53.9,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,37.3,0.6
Quantum of Solace,Daniel Craig,Marc Forster,181.4,8.1
Skyfall,Daniel Craig,Sam Mendes,170.2,14.5
Spectre,Daniel Craig,Sam Mendes,206.3,NaN
The Living Daylights,Timothy Dalton,John Glen,68.8,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,45.1,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,158.3,13.5
Thunderball,Sean Connery,Terence Young,41.9,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,133.9,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,59.9,4.4

In [93]:
actor=bond.pop("Actor")

In [94]:
actor

Film
A View to a Kill                      Roger Moore
Casino Royale                        Daniel Craig
Casino Royale                         David Niven
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: object

In [95]:
del bond["Director"]

In [96]:
bond.head()

                      Year  Box Office  Budget  Bond Actor Salary
Film
A View to a Kill      1985       275.2    54.5                9.1
Casino Royale         2006       581.5   145.3                3.3
Casino Royale         1967       315.0    85.0                NaN
Diamonds Are Forever  1971       442.5    34.7                5.8
Die Another Day       2002       465.4   154.2               17.9

## Create Random Sample with the .sample() Method

In [129]:
bond=pd.read_csv("jamesbond.csv")
bond.set_index("Film" , inplace=True)
bond.sort_index(inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [98]:
bond.sample(n=5)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [99]:
bond.sample(frac=.25)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [100]:
bond.sample(n=2, axis=1)

                                           Director  Budget
Film
A View to a Kill                          John Glen    54.5
Casino Royale                       Martin Campbell   145.3
Casino Royale                            Ken Hughes    85.0
Diamonds Are Forever                   Guy Hamilton    34.7
Die Another Day                        Lee Tamahori   154.2
Dr. No                                Terence Young     7.0
For Your Eyes Only                        John Glen    60.2
From Russia with Love                 Terence Young    12.6
GoldenEye                           Martin Campbell    76.9
Goldfinger                             Guy Hamilton    18.6
Licence to Kill                           John Glen    56.7
Live and Let Die                       Guy Hamilton    30.8
Moonraker                             Lewis Gilbert    91.5
Never Say Never Again                Irvin Kershner    86.0
Octopussy                                 John Glen    53.9
On Her Majesty's Secret Service       Peter R. Hunt    37.3
Quantum of Solace                      Marc Forster   181.4
Skyfall                                  Sam Mendes   170.2
Spectre                                  Sam Mendes   206.3
The Living Daylights                      John Glen    68.8
The Man with the Golden Gun            Guy Hamilton    27.7
The Spy Who Loved Me                  Lewis Gilbert    45.1
The World Is Not Enough               Michael Apted   158.3
Thunderball                           Terence Young    41.9
Tomorrow Never Dies              Roger Spottiswoode   133.9
You Only Live Twice                   Lewis Gilbert    59.9

## The .nsmallest() and .nlargest() Methods

In [101]:
bond.sort_values("Box Office", ascending=False)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [102]:
bond.nlargest(3, columns = "Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [103]:
bond.nsmallest(3, columns = "Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [104]:
bond.nsmallest(1, "Bond Actor Salary")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6

In [105]:
bond["Box Office"].nsmallest()

Film
Licence to Kill                    250.9
A View to a Kill                   275.2
On Her Majesty's Secret Service    291.5
The Living Daylights               313.5
Casino Royale                      315.0
Name: Box Office, dtype: float64

## Filtering with the .where() Method

In [106]:
mask=bond["Actor"]== "Sean Connery"
bond[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [107]:
bond.where(mask)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [108]:
mask1=bond["Box Office"]>800

In [109]:
bond[mask1]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

In [110]:
bond.where(mask1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,2012.0,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
bond.where(mask1 & mask)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN,NaN

## The .query() Method

In [112]:
bond.rename(columns={"Box Office":"Box_Office", "Bond Actor Salary":"Bond_Actor_Salary"}, inplace= True)

In [113]:
bond.head()

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [114]:
bond.columns=[column_name.replace(" ", "_") for column_name in bond.columns]

In [115]:
bond.query('Actor=="David Niven"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [116]:
bond.query("Director=='Lee Tamahori'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [117]:
bond.query("Box_Office == '465.4'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [118]:
bond.query("Box_Office > 465.4")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [119]:
bond.query("Actor=='Roger Moore' and Director=='Sam Mendes'")

Empty DataFrame
Columns: [Year, Actor, Director, Box_Office, Budget, Bond_Actor_Salary]
Index: []

In [120]:
bond.query("Actor=='Roger Moore' or Director=='Sam Mendes'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN

In [121]:
bond.query("Actor in ['Roger Moore', 'Daniel Craig']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN

In [122]:
bond.query("Actor in ['Roger Moore', 'Daniel Craig'] and Director in ['John Glen']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [123]:
bond.query("Actor not in ['Roger Moore', 'Daniel Craig']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [124]:
bond.query("Actor not in ['Roger Moore', 'Daniel Craig'] and Director in ['John Glen']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

## A Review of the .apply() Method on Single Columns

In [130]:
def convert_to_String_and_add_millions(number):
    return str(number)+ " Million!"

In [131]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [132]:
bond["Box Office"]

Film
A View to a Kill                   275.2
Casino Royale                      581.5
Casino Royale                      315.0
Diamonds Are Forever               442.5
Die Another Day                    465.4
Dr. No                             448.8
For Your Eyes Only                 449.4
From Russia with Love              543.8
GoldenEye                          518.5
Goldfinger                         820.4
Licence to Kill                    250.9
Live and Let Die                   460.3
Moonraker                          535.0
Never Say Never Again              380.0
Octopussy                          373.8
On Her Majesty's Secret Service    291.5
Quantum of Solace                  514.2
Skyfall                            943.5
Spectre                            726.7
The Living Daylights               313.5
The Man with the Golden Gun        334.0
The Spy Who Loved Me               533.0
The World Is Not Enough            439.5
Thunderball                        848.1
Tomorrow Never Dies                463.2
You Only Live Twice                514.2
Name: Box Office, dtype: float64

In [133]:
bond["Box Office"]=bond["Box Office"].apply(convert_to_String_and_add_millions)

In [134]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 Million!,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 Million!,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0 Million!,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 Million!,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 Million!,154.2,17.9

In [135]:
bond["Budget"]=bond["Budget"].apply(convert_to_String_and_add_millions)

In [136]:
columns=["Box Office", "Budget", "Bond Actor Salary"]
for col in columns:
    bond[col] = bond[col].apply(convert_to_String_and_add_millions)

In [137]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 Million! Million!,54.5 Million! Million!,9.1 Million!
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 Million! Million!,145.3 Million! Million!,3.3 Million!
Casino Royale,1967,David Niven,Ken Hughes,315.0 Million! Million!,85.0 Million! Million!,nan Million!
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 Million! Million!,34.7 Million! Million!,5.8 Million!
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 Million! Million!,154.2 Million! Million!,17.9 Million!

In [138]:
bond=pd.read_csv("jamesbond.csv")
bond.set_index("Film" , inplace=True)
bond.sort_index(inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## The .apply() Method with Row Values

In [139]:
def good_movie(row):
    actor=row[1]
    budget=row[4]
    if actor=="Pierce Brosnan":
        return "The Best"
    elif actor=="Roger Moore" and budget>40:
        return "Enjoyable"
    else:
        return "I Have No Clue"

In [140]:
mask1=bond.apply(good_movie, axis=1)

In [141]:
bond["Ranking"]=mask1

In [142]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,Ranking
Film,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1,Enjoyable
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,I Have No Clue
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,I Have No Clue
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,I Have No Clue
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,The Best
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,I Have No Clue
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,Enjoyable
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,I Have No Clue
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,The Best
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,I Have No Clue
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,I Have No Clue
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,I Have No Clue
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,Enjoyable
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,I Have No Clue
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,Enjoyable
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,I Have No Clue
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,I Have No Clue
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,I Have No Clue
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN,I Have No Clue
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,I Have No Clue
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,I Have No Clue
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,Enjoyable
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,The Best
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,I Have No Clue
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,The Best
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,I Have No Clue

## The .copy() Method

In [143]:
directors=bond["Director"]

In [144]:
directors.head(3)

Film
A View to a Kill          John Glen
Casino Royale       Martin Campbell
Casino Royale            Ken Hughes
Name: Director, dtype: object

In [145]:
directors["A View to a Kill"]="Mr John Glen"

C:\Users\Bilal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [146]:
directors.head()

Film
A View to a Kill           Mr John Glen
Casino Royale           Martin Campbell
Casino Royale                Ken Hughes
Diamonds Are Forever       Guy Hamilton
Die Another Day            Lee Tamahori
Name: Director, dtype: object

In [147]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,Ranking
Film,,,,,,,
A View to a Kill,1985,Roger Moore,Mr John Glen,275.2,54.5,9.1,Enjoyable
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,I Have No Clue
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,I Have No Clue
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,I Have No Clue
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,The Best

In [149]:
directors=bond["Director"].copy()

In [150]:
directors

Film
A View to a Kill                         Mr John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [151]:
directors["A View to a Kill"]="Mr John Glen"

In [152]:
directors

Film
A View to a Kill                         Mr John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [153]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,Ranking
Film,,,,,,,
A View to a Kill,1985,Roger Moore,Mr John Glen,275.2,54.5,9.1,Enjoyable
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3,I Have No Clue
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,I Have No Clue
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8,I Have No Clue
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9,The Best
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,I Have No Clue
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN,Enjoyable
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,I Have No Clue
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1,The Best
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,I Have No Clue
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9,I Have No Clue
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN,I Have No Clue
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN,Enjoyable
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN,I Have No Clue
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8,Enjoyable
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6,I Have No Clue
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1,I Have No Clue
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5,I Have No Clue
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN,I Have No Clue
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2,I Have No Clue
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN,I Have No Clue
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN,Enjoyable
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5,The Best
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,I Have No Clue
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0,The Best
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4,I Have No Clue